### ISSUE TITLE
[build] plansys2_bt_example fails with compilation errors

### ISSUE THREAD

**Issue by haianos** [PlanSys2/ros2_planning_system_examples#32]
Reproducible by following the instructions at https://plansys2.github.io/tutorials/docs/simple_example.html#requisites

```
ros2_planning_system_examples/plansys2_bt_example/include/plansys2_bt_example/behavior_tree_nodes/Move.hpp:40:18: error: conflicting return type specified for ‘virtual BT::NodeStatus plansys2_bt_tests::Move::on_tick()’
   40 |   BT::NodeStatus on_tick() override;
```

**Comment by fmrico** [comment]
Hi @haianos 

I have just compiled `master` branch in Ubuntu 22.04/Humble, and I cannot reproduce your problem. 

![Captura de pantalla 2022-07-30 10:21:03](https://user-images.githubusercontent.com/3810011/181895433-59704ce9-9589-415c-892d-d9ebecf35406.png)

May you give me more context?
Francisco

**Comment by haianos** [comment]
@fmrico thank you for the very quick answer!

False alarm, I am on `foxy`, just switching to `foxy-devel` does the job.

Closing then.
