### ISSUE TITLE
Parameter 'waypoints' must be initialized in BT example

### ISSUE THREAD

**Issue by DaniGarciaLopez** [PlanSys2/ros2_planning_system_examples#33]
Hi!

I followed the [BT tutorial ](https://plansys2.github.io/tutorials/docs/bt_actions.html) using a fresh humble docker with PlanSys2 compiled by source from the [last commit](https://github.com/PlanSys2/ros2_planning_system/commit/99137b7f96aca3daf4c1667e9d87f67b854fbaee). 

I run in one terminal `ros2 launch plansys2_bt_example plansys2_bt_example_launch.py` and in the other `ros2 run plansys2_terminal plansys2_terminal` with the corresponding PDDL commands. When I send the 'run' command, this error appears in the first terminal and the planner is stuck in the first action at 0%:

```
[bt_action_node-6] [ERROR] [1664902377.208132072] [transport_2]: Failed to create BT with exception: Statically typed parameter 'waypoints' must be initialized.
[bt_action_node-6] [ERROR] [1664902377.208144587] [transport_2]: Transition to activate failed
```

I'm guessing it's something releated to the way the parameters are loaded, but I haven't been able to find the problem yet. Any clues as to why this is happening?

Thanks!

**Comment by fmrico** [comment]
Yes, I found it one week ago, but it has to be fixed here:

https://github.com/PlanSys2/ros2_planning_system/blob/99137b7f96aca3daf4c1667e9d87f67b854fbaee/plansys2_bt_actions/src/plansys2_bt_actions/BTAction.cpp#L70

It should be: `{"--ros-args", "-r", std::string("__node:=") + get_name()});` but I had no time to figure out when it changed, or when it produced the error... I will fix it soon...

Hope it helps!!

**Comment by DaniGarciaLopez** [comment]
This fixed the issue! I'm looking forward to checking the update in plansys2. Thanks Francisco!
